[phases.setup]
nixPkgs = [
  "nodejs_18",
  "chromium",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "glib",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "libdrm",
  "libxkbcommon",
  "mesa"
]

[start]
cmd = "node index.js"
